### ISSUE TITLE
change to markdown from textile

### ISSUE THREAD

**Issue by mhenke** [mhenke/CFML-in-100-minutes#19]
Change to markdown so we can use pandoc http://johnmacfarlane.net/pandoc/  to convert files to pdf, EPUB ebooks, odt, etc.

http://johnmacfarlane.net/pandoc/installing.html

**Comment by russplaysguitar** [comment]
Yikes, looks like the conversion will take a bunch of work.

**Comment by mhenke** [comment]
I used pandoc to convert textile to markdown but it seems the code examples aren't converted correctly. I'll see how textile to html to markdown looks.

**Comment by mhenke** [comment]
it seems these textile to html to markdown worked best but the code samples are still broken.

C:\Users\Owner\Desktop\github\CFML-in-100-minutes>pandoc -s cfml100mins.textile
-f textile -t html -o cfml100mins.html

C:\Users\Owner\Desktop\github\CFML-in-100-minutes>pandoc -s cfml100mins.html -f
html -t markdown -o cfml100mins2.markdown

**Comment by russplaysguitar** [comment]
Maybe try converting the code samples to encoded values, so that the CFML tags don't get misinterpreted as HTML? An encoder like this might help: http://meyerweb.com/eric/tools/dencoder/

**Comment by mhenke** [comment]
ah, i think i got it. Take a look
