### ISSUE TITLE
search for "m space and replace with 'm space

### ISSUE THREAD

**Issue by mhenke** [mhenke/CFML-in-100-minutes#29]
search for "m space and replace with 'm space

**Comment by designfrontier** [comment]
Just want to clarify that you mean the literal string ["m ] being replaces with ['m ]

**Comment by mhenke** [comment]
Yeah, Peter F found one case so I am guessing there are more. I replaced single goofy quotes with double quotes a couple weeks ago and thought I fixed the appropriate single quotes

**Comment by designfrontier** [comment]
Ok if this is still open this evening I'll knock it out and send you a pull request

**Comment by designfrontier** [comment]
Had a couple of minutes and ran a regex over it. Looks like there was only the one instance and you had fixed it.

**Comment by mhenke** [comment]
thanks
